version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend  # Docker baut ein eigenes Image für diesen Container
    ports:
      - "8000:80"  # hört innen auf 80, von außen auf 8000 zugreifbar
    volumes:
      - ./backend:/app    # Lokaler Ordner wird in den Container gemountet unter /app
    environment:
      - MONGO_URI=mongodb://mongo:27017/   # Umgebungsvariable, damit Backend weiß wie es DB erreicht
      - PORT=80 
    networks:
      - app-net
    depends_on:
      - mongo   # Erst wen mongo gestartet dann starte backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "5001:80"  
    networks:
      - app-net
    environment:
      - REACT_APP_API_URL=http://backend:80

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  
    networks:
      - app-net

networks:
  app-net:  #erstelle NW

volumes:
  mongo-data:  # erstelle Volumen Volumes -> Daten dauerhaft speichern auch wenn Container neugestartet wird
