version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:80"  
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/  
    networks:
      - app-net
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "5001:80"  
    networks:
      - app-net
    environment:
      - REACT_APP_API_URL=http://backend:80 

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  
    networks:
      - app-net

networks:
  app-net:

volumes:
  mongo-data:  
