version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:80"  # außen 8000 → Container-Port 80
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/  # Verbindung zu MongoDB im Container
    networks:
      - app-net
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "5001:80"  # außen 5001 → Container-Port 80
    networks:
      - app-net
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Verbindung zum Backend über den Service-Namen

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-net

networks:
  app-net:
