apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: frontend:latest
      ports:
        - containerPort: 80
      env:
        - name: REACT_APP_API_URL
          value: /api
