apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumes:
    - name: mongo-data
      emptyDir: {}
